import { NextResponse } from "next/server";
import { z } from "zod";
import { authenticateApiRequest } from "@/lib/api-auth";
import { sql } from "@/lib/db";
import { preconditionResponse,requireIfMatch,staleResourceResponse,versionedJson } from "@/lib/http-concurrency";

const schema=z.object({name:z.string().trim().min(1).max(200).optional(),description:z.string().trim().max(1000).optional(),folder:z.string().trim().max(200).optional(),status:z.enum(["active","archived"]).optional()}).refine(value=>Object.keys(value).length>0);

export async function GET(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"templates:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});const{id}=await context.params;const[block]=await sql`SELECT * FROM reusable_blocks WHERE id=${id}`;if(!block)return NextResponse.json({error:{code:"not_found",message:"Bloque no encontrado"}},{status:404});return versionedJson(request,block,"reusable-block",id,block.revision);}

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"templates:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const{id}=await context.params;const revision=requireIfMatch(request,"reusable-block",id);const input=schema.parse(await request.json());const[block]=await sql`UPDATE reusable_blocks SET name=COALESCE(${input.name??null},name),description=COALESCE(${input.description??null},description),folder=COALESCE(${input.folder??null},folder),archived_at=CASE WHEN ${input.status??null}='archived' THEN now() WHEN ${input.status??null}='active' THEN NULL ELSE archived_at END,updated_by=${principal.kind==="session"?principal.id:null},updated_at=now() WHERE id=${id} AND revision=${revision} RETURNING *`;if(!block)return staleResourceResponse();return versionedJson(request,block,"reusable-block",id,block.revision);}catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;if(error instanceof z.ZodError)return NextResponse.json({error:{code:"validation_error",message:"Datos no válidos",issues:error.issues}},{status:422});throw error;}}

export async function DELETE(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"templates:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const{id}=await context.params;const revision=requireIfMatch(request,"reusable-block",id);const[block]=await sql`UPDATE reusable_blocks SET archived_at=now(),updated_by=${principal.kind==="session"?principal.id:null},updated_at=now() WHERE id=${id} AND revision=${revision} AND archived_at IS NULL RETURNING id,revision`;if(!block)return staleResourceResponse();await sql`INSERT INTO audit_log(action,entity_type,entity_id,user_id,api_key_id)VALUES('archive','reusable_block',${id},${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null})`;return versionedJson(request,{archived:true},"reusable-block",id,block.revision);}catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;throw error;}}
