FROM postgres:17-alpine@sha256:742f40ea20b9ff2ff31db5458d127452988a2164df9e17441e191f3b72252193
RUN apk add --no-cache openssl
COPY scripts/backup.sh scripts/backup-loop.sh scripts/restore.sh scripts/restore-test.sh /opt/serenity/
RUN chmod 0555 /opt/serenity/*.sh
ENTRYPOINT []
CMD ["/opt/serenity/backup-loop.sh"]
