import { NextResponse } from "next/server";
import { z } from "zod";
import { authenticateApiRequest } from "@/lib/api-auth";
import { sql } from "@/lib/db";
import { preconditionResponse,requireIfMatch,staleResourceResponse,versionedJson } from "@/lib/http-concurrency";
const schema=z.object({status:z.enum(["active","disabled"]),events:z.array(z.string()).max(50).optional()});
export async function GET(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"webhooks:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});const{id}=await context.params;const[row]=await sql`SELECT id,revision,name,url,events,filters,status,failure_count,last_success_at,last_failure_at,created_at,updated_at FROM webhook_endpoints WHERE id=${id}`;if(!row)return NextResponse.json({error:{code:"not_found",message:"Webhook no encontrado"}},{status:404});return versionedJson(request,row,"webhook",id,row.revision);}
export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"webhooks:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const{id}=await context.params;const revision=requireIfMatch(request,"webhook",id);const input=schema.parse(await request.json());const[row]=await sql`UPDATE webhook_endpoints SET status=${input.status},events=COALESCE(${input.events??null},events),updated_at=now() WHERE id=${id} AND revision=${revision} RETURNING id,revision,name,url,events,filters,status,failure_count,last_success_at,last_failure_at,updated_at`;if(!row)return staleResourceResponse();return versionedJson(request,row,"webhook",id,row.revision);}catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;if(error instanceof z.ZodError)return NextResponse.json({error:{code:"validation_error",message:"Datos no válidos",issues:error.issues}},{status:422});throw error;}}
export async function DELETE(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"webhooks:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const{id}=await context.params;const revision=requireIfMatch(request,"webhook",id);const[row]=await sql`UPDATE webhook_endpoints SET status='disabled',updated_at=now() WHERE id=${id} AND revision=${revision} RETURNING id,revision`;if(!row)return staleResourceResponse();return versionedJson(request,{disabled:true},"webhook",id,row.revision);}catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;throw error;}}
