import { loadPreferenceCenter } from "@/lib/public-preferences";

type Field={key:string;label:string;type:string;help_text:string;options:unknown[];required:boolean};
function fieldInput(subscription:{list_id:string;custom_values:Record<string,unknown>},field:Field){const name=`field.${subscription.list_id}.${field.key}.${field.type}`;const value=subscription.custom_values?.[field.key];if(field.type==="boolean")return <input type="checkbox" name={name} value="true" defaultChecked={value===true}/>;if(field.type==="select")return <select name={name} defaultValue={String(value??"")}><option value="">Sin seleccionar</option>{field.options.map(option=><option key={String(option)} value={String(option)}>{String(option)}</option>)}</select>;if(field.type==="multiselect"){const selected=Array.isArray(value)?value.map(String):[];return <select name={name} multiple defaultValue={selected}>{field.options.map(option=><option key={String(option)} value={String(option)}>{String(option)}</option>)}</select>;}if(field.type==="textarea")return <textarea name={name} defaultValue={String(value??"")}/>;const inputType={integer:"number",decimal:"number",date:"date",datetime:"datetime-local",email:"email",url:"url"}[field.type]??"text";return <input type={inputType} step={field.type==="decimal"?"any":undefined} name={name} defaultValue={String(value??"")}/>;}

export default async function PreferencesPage({params}:{params:Promise<{token:string}>}){
  const{token}=await params;const center=await loadPreferenceCenter(decodeURIComponent(token));
  if(!center)return <main className="public-page"><section className="public-card"><div className="brand-mark brand-mark-large">S</div><p className="eyebrow">Centro de preferencias</p><h1>Este enlace no es válido</h1><p>El enlace puede haber caducado o haber sido revocado. Usa uno de tus emails recientes para volver a entrar.</p></section></main>;
  const city=String(center.contact.custom_fields?.city??"");const country=String(center.contact.custom_fields?.country??"");
  return <main className="public-page preference-page"><section className="public-card preference-card"><div className="brand-mark brand-mark-large">S</div><p className="eyebrow">Centro de preferencias</p><h1>Elige qué quieres recibir</h1><p>Los cambios se aplican únicamente a las comunicaciones promocionales. Los mensajes transaccionales legítimos se gestionan aparte.</p><form className="preference-form" action="/api/public/preferences" method="post"><input type="hidden" name="token" value={token}/><fieldset><legend>Tus datos</legend><div className="form-grid"><label>Nombre<input name="first_name" defaultValue={center.contact.first_name}/></label><label>Apellidos<input name="last_name" defaultValue={center.contact.last_name}/></label><label>Teléfono<input name="phone" defaultValue={center.contact.phone}/></label><label>Ciudad<input name="city" defaultValue={city}/></label><label>País<input name="country" defaultValue={country}/></label><label>Email<input value={center.contact.email} disabled/></label></div></fieldset><fieldset><legend>Tus listas</legend><div className="preference-lists">{center.subscriptions.map(subscription=><article key={subscription.id} style={{"--list-color":subscription.list_color} as React.CSSProperties}><label className="preference-toggle"><span><strong>{subscription.list_name}</strong><small>{subscription.list_description||`Origen: ${subscription.source}`}</small></span><input type="checkbox" name="active_list_ids" value={subscription.list_id} defaultChecked={subscription.status==="active"} disabled={subscription.status==="pending"}/></label>{subscription.status==="pending"&&<p className="pending-note">Pendiente de confirmar por email.</p>}{(subscription.fields as Field[]).length>0&&<div className="preference-fields">{(subscription.fields as Field[]).map(field=><label key={field.key}>{field.label}{fieldInput(subscription,field)}{field.help_text&&<small>{field.help_text}</small>}</label>)}</div>}</article>)}</div></fieldset><div className="preference-actions"><button className="button button-secondary" type="submit" name="action" value="unsubscribe_all">Dar de baja todas las comunicaciones</button><button className="button button-primary" type="submit" name="action" value="save">Guardar preferencias</button></div></form></section></main>;
}
