export type VisualBlockType="heading"|"text"|"button"|"image"|"divider"|"spacer"|"quote"|"list";
export type VisualBlock={id:string;type:VisualBlockType;content:string;url?:string;link_url?:string;asset_id?:string;alt?:string;color?:string;align?:"left"|"center"|"right";size?:number};
export type VisualTheme={outer_bg:string;content_bg:string;text_color:string;primary_color:string;font_family:"Arial"|"Georgia"|"Verdana"|"Tahoma";width:number};

export const defaultVisualTheme:VisualTheme={outer_bg:"#f3f0e9",content_bg:"#ffffff",text_color:"#263536",primary_color:"#183e3f",font_family:"Arial",width:620};

function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function safeColor(value:string|undefined,fallback:string){return /^#[0-9a-f]{6}$/i.test(value??"")?value!:fallback;}
function safeUrl(value:string|undefined,baseUrl=""){if(!value)return"#";if(value.startsWith("{{")&&value.endsWith("}}"))return escapeHtml(value);if(value.startsWith("/")&&!baseUrl)return escapeHtml(value);try{const url=new URL(value,baseUrl||undefined);if(!["http:","https:","mailto:","tel:"].includes(url.protocol))return"#";return escapeHtml(url.toString());}catch{return"#";}}
function row(id:string,content:string,padding="0 38px"){return`<tr data-block-id="${escapeHtml(id)}"><td style="padding:${padding};">${content}</td></tr>`;}

export function compileVisualEmail(blocks:VisualBlock[],theme:Partial<VisualTheme>={},previewText="",baseUrl=""){
  const resolved={...defaultVisualTheme,...theme};const width=Math.min(760,Math.max(480,Number(resolved.width)||620));const outer=safeColor(resolved.outer_bg,defaultVisualTheme.outer_bg);const contentBg=safeColor(resolved.content_bg,defaultVisualTheme.content_bg);const textColor=safeColor(resolved.text_color,defaultVisualTheme.text_color);const primary=safeColor(resolved.primary_color,defaultVisualTheme.primary_color);const font=["Arial","Georgia","Verdana","Tahoma"].includes(resolved.font_family)?resolved.font_family:"Arial";
  const rows=blocks.map(block=>{const align=block.align??"left";const color=safeColor(block.color,block.type==="button"?primary:textColor);if(block.type==="heading")return row(block.id,`<h1 style="margin:0 0 20px;color:${color};font-family:Georgia,Times,serif;font-size:${Math.min(54,Math.max(20,block.size??38))}px;line-height:1.15;font-weight:500;text-align:${align};">${escapeHtml(block.content)}</h1>`);if(block.type==="text")return row(block.id,`<p style="margin:0 0 20px;color:${color};font-family:${font},Arial,sans-serif;font-size:${Math.min(24,Math.max(12,block.size??17))}px;line-height:1.65;text-align:${align};">${escapeHtml(block.content).replaceAll("\n","<br>")}</p>`);if(block.type==="quote")return row(block.id,`<blockquote style="margin:0 0 22px;padding:4px 0 4px 18px;border-left:3px solid ${primary};color:${color};font-family:Georgia,serif;font-size:${Math.min(26,Math.max(13,block.size??18))}px;line-height:1.55;text-align:${align};">${escapeHtml(block.content).replaceAll("\n","<br>")}</blockquote>`);if(block.type==="list"){const items=block.content.split("\n").map(item=>item.trim()).filter(Boolean).map(item=>`<li style="margin:0 0 8px;">${escapeHtml(item)}</li>`).join("");return row(block.id,`<ul style="margin:0 0 20px;padding-left:22px;color:${color};font-family:${font},Arial,sans-serif;font-size:${Math.min(22,Math.max(12,block.size??16))}px;line-height:1.5;text-align:${align};">${items}</ul>`);}if(block.type==="button"){const href=safeUrl(block.url,baseUrl);return row(block.id,`<table role="presentation" cellspacing="0" cellpadding="0" border="0" align="${align}"><tr><td bgcolor="${color}" style="border-radius:5px;"><a href="${href}" style="display:inline-block;padding:13px 20px;border:1px solid ${color};border-radius:5px;background:${color};color:#ffffff;font:bold 14px ${font},Arial,sans-serif;text-decoration:none;">${escapeHtml(block.content)}</a></td></tr></table>`,`4px 38px 24px`);}if(block.type==="image"){const src=safeUrl(block.url,baseUrl);const image=`<img src="${src}" alt="${escapeHtml(block.alt??"")}" width="544" style="display:block;width:100%;max-width:544px;height:auto;margin:${align==="center"?"0 auto":align==="right"?"0 0 0 auto":"0"};border:0;outline:none;text-decoration:none;">`;const content=block.link_url?`<a href="${safeUrl(block.link_url,baseUrl)}" style="text-decoration:none;">${image}</a>`:image;return row(block.id,content,`0 38px 22px`);}if(block.type==="divider")return row(block.id,`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td style="border-top:1px solid ${color};font-size:0;line-height:0;">&nbsp;</td></tr></table>`,`2px 38px 24px`);return row(block.id,"&nbsp;",`0 38px ${Math.min(120,Math.max(4,block.size??24))}px`);}).join("");
  const preheader=previewText?`<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;mso-hide:all;">${escapeHtml(previewText)}&#847;&zwnj;&nbsp;</div>`:"";
  return`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title></title><style>@media only screen and (max-width:620px){.sm-shell{width:100%!important}.sm-content td{padding-left:22px!important;padding-right:22px!important}}</style><!--[if mso]><style>table{border-collapse:collapse}td{font-family:Arial,sans-serif}</style><![endif]--></head><body style="margin:0;padding:0;background:${outer};-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">${preheader}<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="${outer}"><tr><td align="center" style="padding:28px 12px;"><table role="presentation" class="sm-shell sm-content" width="${width}" cellspacing="0" cellpadding="0" border="0" bgcolor="${contentBg}" style="width:${width}px;max-width:100%;background:${contentBg};">${rows}</table></td></tr></table></body></html>`;
}
