import { randomBytes } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { sql } from "@/lib/db";
import { apiError, requireApiSession } from "@/lib/http";
import { headerText } from "@/lib/validation";

const schema=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(1),key:z.string().regex(/^[a-z][a-z0-9_-]+$/).optional(),channel:z.enum(["marketing","transactional"]).default("marketing"),subject:headerText(1,998),preview_text:z.string().max(200).default(""),html_content:z.string().min(1),text_content:z.string().default("")});
function keyFor(name:string){const base=name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,100)||"plantilla";return`${base}_${randomBytes(3).toString("hex")}`;}
export async function POST(request:Request){const unauthorized=await requireApiSession("templates:write");if(unauthorized)return unauthorized;try{const input=schema.parse(await request.json());const key=input.key??keyFor(input.name);const row=await sql.begin(async tx=>{const[template]=await tx<{id:string}[]>`INSERT INTO templates(key,name,channel,format,status,subject,preview_text,html_content,text_content)VALUES(${key},${input.name},${input.channel},'html','published',${input.subject},${input.preview_text},${input.html_content},${input.text_content})RETURNING id`;const[version]=await tx<{id:string}[]>`INSERT INTO template_versions(template_id,version_number,status,source_format,subject,preview_text,html_content,text_content,published_at)VALUES(${template.id},1,'published','html',${input.subject},${input.preview_text},${input.html_content},${input.text_content},now())RETURNING id`;const[updated]=await tx`UPDATE templates SET published_version_id=${version.id} WHERE id=${template.id} RETURNING *`;return updated;});return NextResponse.json(row,{status:201});}catch(error){return apiError(error);}}
export async function PATCH(request:Request){const unauthorized=await requireApiSession("templates:write");if(unauthorized)return unauthorized;try{const input=schema.extend({id:z.string().uuid()}).parse(await request.json());const row=await sql.begin(async tx=>{const[template]=await tx<{id:string}[]>`SELECT id FROM templates WHERE id=${input.id} AND status<>'archived' FOR UPDATE`;if(!template)throw new Error("Plantilla no encontrada");const[version]=await tx<{id:string}[]>`INSERT INTO template_versions(template_id,version_number,status,source_format,subject,preview_text,html_content,text_content,published_at)SELECT ${input.id},COALESCE(max(version_number)+1,1),'published','html',${input.subject},${input.preview_text},${input.html_content},${input.text_content},now() FROM template_versions WHERE template_id=${input.id} RETURNING id`;await tx`UPDATE template_versions SET status='archived' WHERE template_id=${input.id} AND status='published' AND id<>${version.id}`;const[updated]=await tx`UPDATE templates SET name=${input.name},channel=${input.channel},subject=${input.subject},preview_text=${input.preview_text},html_content=${input.html_content},text_content=${input.text_content},published_version_id=${version.id},status='published',updated_at=now() WHERE id=${input.id} RETURNING *`;return updated;});return NextResponse.json(row);}catch(error){return apiError(error);}}
export async function DELETE(request:Request){const unauthorized=await requireApiSession("templates:write");if(unauthorized)return unauthorized;try{const{id}=z.object({id:z.string().uuid()}).parse(await request.json());await sql`UPDATE templates SET status='archived',archived_at=now(),updated_at=now() WHERE id=${id}`;return NextResponse.json({ok:true});}catch(error){return apiError(error);}}
