import { NextResponse } from "next/server";
import { z } from "zod";
import { authenticateApiRequest } from "@/lib/api-auth";
import { sql } from "@/lib/db";
import { preconditionResponse, requireIfMatch, staleResourceResponse, versionedJson } from "@/lib/http-concurrency";

const schema=z.object({first_name:z.string().trim().max(200).optional(),last_name:z.string().trim().max(200).optional(),phone:z.string().trim().max(80).optional(),language:z.string().max(12).optional(),timezone:z.string().max(80).optional(),fields:z.record(z.string(),z.unknown()).optional()}).refine(value=>Object.keys(value).length>0);
export async function GET(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"contacts:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});const{id}=await context.params;const[contact]=await sql<{merged_into_contact_id?:string;anonymized_at?:Date;revision:number;id:string;[key:string]:unknown}[]>`SELECT * FROM contacts WHERE id=${id}`;if(!contact)return NextResponse.json({error:{code:"not_found",message:"Contacto no encontrado"}},{status:404});if(contact.merged_into_contact_id)return NextResponse.json({error:{code:"contact_merged",message:"El contacto fue fusionado",survivor_contact_id:contact.merged_into_contact_id}},{status:410});if(contact.anonymized_at)return NextResponse.json({error:{code:"contact_anonymized",message:"El contacto fue anonimizado"}},{status:410});const subscriptions=await sql`SELECT s.*,l.key AS list_key,l.name AS list_name FROM subscriptions s JOIN lists l ON l.id=s.list_id WHERE s.contact_id=${id} ORDER BY s.created_at`;const consent=await sql`SELECT id,list_id,subscription_id,action,source,consent_text,legal_basis,detail,occurred_at FROM consent_events WHERE contact_id=${id} ORDER BY occurred_at DESC`;const merges=await sql`SELECT id,source_email_hash,field_strategy,reason,detail,merged_at FROM contact_merges WHERE survivor_contact_id=${id} ORDER BY merged_at DESC`;return versionedJson(request,{...contact,subscriptions,consent,merges},"contact",id,contact.revision);}
export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"contacts:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const{id}=await context.params;const revision=requireIfMatch(request,"contact",id);const input=schema.parse(await request.json());const fields=input.fields?JSON.parse(JSON.stringify(input.fields)) as never:null;const[contact]=await sql`UPDATE contacts SET first_name=COALESCE(${input.first_name??null},first_name),last_name=COALESCE(${input.last_name??null},last_name),phone=COALESCE(${input.phone??null},phone),language=COALESCE(${input.language??null},language),timezone=COALESCE(${input.timezone??null},timezone),custom_fields=CASE WHEN ${fields?true:false} THEN custom_fields||${fields?sql.json(fields):sql.json({})} ELSE custom_fields END,updated_at=now() WHERE id=${id} AND revision=${revision} AND merged_into_contact_id IS NULL AND anonymized_at IS NULL RETURNING *`;if(!contact)return staleResourceResponse();return versionedJson(request,contact,"contact",id,contact.revision);}catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;if(error instanceof z.ZodError)return NextResponse.json({error:{code:"validation_error",message:"Datos no válidos",issues:error.issues}},{status:422});throw error;}}
