import { mkdir,writeFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import { authenticateApiRequest } from "@/lib/api-auth";
import { prepareAsset } from "@/lib/assets";
import { sql } from "@/lib/db";
import { resourceEtag,versionedJson } from "@/lib/http-concurrency";

export const runtime="nodejs";
const maxBytes=5*1024*1024;

export async function GET(request:Request){const principal=await authenticateApiRequest(request,"templates:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});const url=new URL(request.url);const q=url.searchParams.get("q")?.trim()??"";const folder=url.searchParams.get("folder");const includeArchived=url.searchParams.get("include_archived")==="true";const limit=Math.min(Math.max(Number(url.searchParams.get("limit")??100),1),300);const data=await sql`SELECT a.id,a.revision,a.name,a.original_name,a.mime_type,a.byte_size,a.width,a.height,a.folder,a.alt_text,a.sha256,a.created_at,a.updated_at,a.archived_at,count(u.asset_id)::int AS usage_count FROM assets a LEFT JOIN asset_usages u ON u.asset_id=a.id WHERE (${includeArchived} OR a.archived_at IS NULL) AND (${q}='' OR a.name ILIKE ${`%${q}%`} OR a.original_name ILIKE ${`%${q}%`}) AND (${folder}::text IS NULL OR a.folder=${folder}) GROUP BY a.id ORDER BY a.updated_at DESC LIMIT ${limit}`;return NextResponse.json({data:data.map(item=>({...item,url:`/api/v1/assets/${item.id}/content`,etag:resourceEtag("asset",item.id,item.revision)}))});}

export async function POST(request:Request){const principal=await authenticateApiRequest(request,"templates:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const form=await request.formData();const file=form.get("file");if(!(file instanceof File))return NextResponse.json({error:{code:"validation_error",message:"Selecciona un archivo"}},{status:422});if(file.size<=0||file.size>maxBytes)return NextResponse.json({error:{code:"validation_error",message:"El archivo debe pesar entre 1 byte y 5 MB"}},{status:422});const buffer=Buffer.from(await file.arrayBuffer());const prepared=prepareAsset(buffer,file.type);const existing=await sql`SELECT id,revision,name,original_name,mime_type,byte_size,width,height,folder,alt_text,sha256,created_at,updated_at,archived_at FROM assets WHERE sha256=${prepared.sha256} AND archived_at IS NULL LIMIT 1`;if(existing[0])return versionedJson(request,{...existing[0],url:`/api/v1/assets/${existing[0].id}/content`,duplicate:true},"asset",existing[0].id,existing[0].revision);await mkdir(path.dirname(prepared.absolutePath),{recursive:true});await writeFile(prepared.absolutePath,buffer,{flag:"wx"});const originalName=file.name.slice(0,240);const name=String(form.get("name")||file.name).trim().slice(0,200)||"Archivo";const folder=String(form.get("folder")??"").trim().slice(0,200);const altText=String(form.get("alt_text")??"").trim().slice(0,500);const[asset]=await sql`INSERT INTO assets(id,name,original_name,storage_key,mime_type,byte_size,width,height,folder,alt_text,sha256,created_by)VALUES(${prepared.id},${name},${originalName},${prepared.storageKey},${prepared.mimeType},${buffer.length},${prepared.width},${prepared.height},${folder},${altText},${prepared.sha256},${principal.kind==="session"?principal.id:null})RETURNING id,revision,name,original_name,mime_type,byte_size,width,height,folder,alt_text,sha256,created_at,updated_at,archived_at`;await sql`INSERT INTO audit_log(action,entity_type,entity_id,user_id,api_key_id,detail)VALUES('create','asset',${asset.id},${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null},${sql.json({mime_type:prepared.mimeType,byte_size:buffer.length})})`;return versionedJson(request,{...asset,url:`/api/v1/assets/${asset.id}/content`,duplicate:false},"asset",asset.id,asset.revision,201);}catch(error){return NextResponse.json({error:{code:"validation_error",message:error instanceof Error?error.message:"No se pudo subir el archivo"}},{status:422});}}
