import { NextResponse } from "next/server";
import { z } from "zod";
import { authenticateApiRequest } from "@/lib/api-auth";
import { sql } from "@/lib/db";
import { getCampaignExperimentReport } from "@/lib/campaign-experiments";
import { headerText } from "@/lib/validation";
import { preconditionResponse,requireIfMatch,staleResourceResponse,versionedJson } from "@/lib/http-concurrency";

const updateSchema=z.object({
  version:z.number().int().positive(),name:z.string().trim().min(1).max(200).optional(),list_id:z.string().uuid().optional(),subject:headerText(1,998).optional(),preview_text:z.string().max(200).optional(),
  from:z.object({name:headerText(1,200),email:z.email()}).optional(),reply_to:z.union([z.email(),z.literal("")]).optional(),template_version_id:z.string().uuid().optional(),content:z.object({html:z.string().min(1).max(2_000_000),text:z.string().max(2_000_000).default("")}).optional(),
  segment_id:z.string().uuid().nullable().optional(),exclusion_segment_ids:z.array(z.string().uuid()).max(20).optional(),track_opens:z.boolean().nullable().optional(),track_clicks:z.boolean().nullable().optional(),
  approval_required:z.boolean().optional(),
}).refine(value=>!(value.template_version_id&&value.content),{message:"Usa una versión de plantilla o HTML directo, no ambos"});
type EditableCampaign={id:string;name:string;list_id:string;subject:string;preview_text:string;from_name:string;from_email:string;reply_to:string;template_id:string|null;template_version_id:string|null;content_source:"template"|"direct";html_content:string;text_content:string;target_id:string|null;exclusion_segment_ids:string[];track_opens:boolean|null;track_clicks:boolean|null;status:string;launch_idempotency_key:string|null;version:number;approval_required:boolean;approved_by:string|null;approved_api_key_id:string|null;approved_at:Date|null;approved_version:number|null};

export async function GET(request:Request,context:{params:Promise<{id:string}>}){
  const principal=await authenticateApiRequest(request,"campaigns:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});
  const {id}=await context.params;const [campaign]=await sql`SELECT * FROM campaigns WHERE id=${id}`;if(!campaign)return NextResponse.json({error:{code:"not_found",message:"Campaña no encontrada"}},{status:404});
  const recipients=await sql`SELECT id,email,status,variant_id,experiment_phase,queued_at,sent_at,delivered_at,opened_at,clicked_at,open_count,click_count,failure_reason FROM campaign_recipients WHERE campaign_id=${id} ORDER BY created_at LIMIT 200`;
  const exclusions=await sql`SELECT reason,count(*)::int AS count FROM campaign_exclusions WHERE campaign_id=${id} GROUP BY reason ORDER BY reason`;
  const transitions=await sql`SELECT id,from_status,to_status,action,detail,created_at FROM campaign_transitions WHERE campaign_id=${id} ORDER BY created_at,id`;
  const approval_comments=await sql`SELECT ac.id,ac.action,ac.comment,ac.campaign_version,ac.created_at,ac.user_id,ac.api_key_id,
    COALESCE(u.name,k.name,'Sistema') AS actor_name,CASE WHEN ac.user_id IS NOT NULL THEN 'user' WHEN ac.api_key_id IS NOT NULL THEN 'api_key' ELSE 'system' END AS actor_kind
    FROM campaign_approval_comments ac LEFT JOIN users u ON u.id=ac.user_id LEFT JOIN api_keys k ON k.id=ac.api_key_id
    WHERE ac.campaign_id=${id} ORDER BY ac.created_at,ac.id`;
  const experiment=await getCampaignExperimentReport(id);return versionedJson(request,{...campaign,recipients,exclusions,transitions,approval_comments,experiment},"campaign",id,campaign.version);
}

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){
  const principal=await authenticateApiRequest(request,"campaigns:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});
  try{
    const{id}=await context.params;const input=updateSchema.parse(await request.json());if(request.headers.has("if-match")&&requireIfMatch(request,"campaign",id)!==input.version)return staleResourceResponse();const[current]=await sql<EditableCampaign[]>`SELECT * FROM campaigns WHERE id=${id} AND archived_at IS NULL`;
    if(!current)return NextResponse.json({error:{code:"not_found",message:"Campaña no encontrada"}},{status:404});
    if(!["draft","scheduled"].includes(current.status)||current.launch_idempotency_key)return NextResponse.json({error:{code:"invalid_state",message:"Solo se pueden editar borradores o campañas programadas que aún no han comenzado"}},{status:409});
    const listId=input.list_id??current.list_id;if(input.list_id){const[list]=await sql`SELECT id FROM lists WHERE id=${listId} AND status='active'`;if(!list)return NextResponse.json({error:{code:"list_not_found",message:"Lista no encontrada"}},{status:404});}
    const segmentId=input.segment_id===undefined?current.target_id:input.segment_id;if(segmentId){const[segment]=await sql`SELECT id FROM segments WHERE id=${segmentId} AND status='active' AND (list_id IS NULL OR list_id=${listId})`;if(!segment)return NextResponse.json({error:{code:"segment_not_found",message:"El segmento no pertenece a la lista"}},{status:422});}
    let content={source:current.content_source,templateId:current.template_id,versionId:current.template_version_id,html:current.html_content,text:current.text_content};
    if(input.content)content={source:"direct",templateId:null,versionId:null,html:input.content.html,text:input.content.text};
    if(input.template_version_id){const[version]=await sql<{id:string;template_id:string;html_content:string;text_content:string}[]>`SELECT v.id,v.template_id,v.html_content,v.text_content FROM template_versions v JOIN templates t ON t.id=v.template_id WHERE v.id=${input.template_version_id} AND v.status='published' AND t.status='published' AND t.channel='marketing'`;if(!version)return NextResponse.json({error:{code:"template_not_found",message:"Versión de marketing no encontrada"}},{status:404});content={source:"template",templateId:version.template_id,versionId:version.id,html:version.html_content,text:version.text_content};}
    const approvalRequired=input.approval_required??current.approval_required;const[existingExperiment]=await sql<{id:string}[]>`SELECT id FROM campaign_experiments WHERE campaign_id=${id} AND status='configured'`;
    const meaningfulChange=(input.list_id!==undefined&&input.list_id!==current.list_id)||(input.subject!==undefined&&input.subject!==current.subject)||(input.preview_text!==undefined&&input.preview_text!==current.preview_text)||(input.from!==undefined&&(input.from.name!==current.from_name||input.from.email!==current.from_email))||(input.reply_to!==undefined&&input.reply_to!==current.reply_to)||(input.template_version_id!==undefined&&input.template_version_id!==current.template_version_id)||(input.content!==undefined&&(input.content.html!==current.html_content||input.content.text!==current.text_content))||(input.segment_id!==undefined&&input.segment_id!==current.target_id)||(input.exclusion_segment_ids!==undefined&&JSON.stringify(input.exclusion_segment_ids)!==JSON.stringify(current.exclusion_segment_ids))||(input.track_opens!==undefined&&input.track_opens!==current.track_opens)||(input.track_clicks!==undefined&&input.track_clicks!==current.track_clicks);
    const hasCurrentApproval=Boolean(current.approved_at&&current.approved_version===current.version);const invalidatesApproval=hasCurrentApproval&&(meaningfulChange||input.approval_required===false);const approvalBecameRequired=!current.approval_required&&approvalRequired;const returnToDraft=current.status==="scheduled"&&approvalRequired&&(invalidatesApproval||approvalBecameRequired);
    const snapshot=JSON.parse(JSON.stringify({source:content.source,template_version_id:content.versionId,html:content.html,text:content.text,created_at:new Date().toISOString()})) as never;
    const[row]=await sql`UPDATE campaigns SET name=${input.name??current.name},list_id=${listId},subject=${input.subject??current.subject},preview_text=${input.preview_text??current.preview_text},from_name=${input.from?.name??current.from_name},from_email=${input.from?.email??current.from_email},reply_to=${input.reply_to??current.reply_to},template_id=${content.templateId},template_version_id=${content.versionId},content_source=${content.source},html_content=${content.html},text_content=${content.text},content_snapshot=${sql.json(snapshot)},target_type=${segmentId?"segment":"all"},target_id=${segmentId},exclusion_segment_ids=${input.exclusion_segment_ids??current.exclusion_segment_ids},track_opens=${input.track_opens===undefined?current.track_opens:input.track_opens},track_clicks=${input.track_clicks===undefined?current.track_clicks:input.track_clicks},approval_required=${approvalRequired},approved_by=CASE WHEN ${invalidatesApproval||input.approval_required===false} THEN NULL ELSE approved_by END,approved_api_key_id=CASE WHEN ${invalidatesApproval||input.approval_required===false} THEN NULL ELSE approved_api_key_id END,approved_at=CASE WHEN ${invalidatesApproval||input.approval_required===false} THEN NULL ELSE approved_at END,approved_version=CASE WHEN ${invalidatesApproval||input.approval_required===false} THEN NULL WHEN approved_version=version THEN version+1 ELSE approved_version END,status=${returnToDraft?"draft":current.status},scheduled_at=CASE WHEN ${returnToDraft} THEN NULL ELSE scheduled_at END,version=version+1,updated_at=now() WHERE id=${id} AND version=${input.version} RETURNING *`;
    if(!row)return NextResponse.json({error:{code:"version_conflict",message:"La campaña cambió en otra sesión; recarga antes de guardar"}},{status:409});
    if(meaningfulChange&&existingExperiment){await sql`DELETE FROM campaign_experiments WHERE id=${existingExperiment.id}`;await sql`INSERT INTO campaign_transitions(campaign_id,from_status,to_status,action,user_id,api_key_id,detail)VALUES(${id},${current.status},${row.status},'experiment_invalidated',${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null},${sql.json({reason:"campaign_updated",version:row.version})})`;}
    if(invalidatesApproval){await sql`INSERT INTO campaign_approval_comments(campaign_id,action,comment,campaign_version,user_id,api_key_id)VALUES(${id},'invalidated','Aprobación invalidada automáticamente por cambios en la campaña',${row.version},${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null})`;await sql`INSERT INTO campaign_transitions(campaign_id,from_status,to_status,action,user_id,api_key_id,detail)VALUES(${id},${current.status},${row.status},'approval_invalidated',${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null},${sql.json({previous_version:current.version,version:row.version})})`;}
    await sql`INSERT INTO audit_log(action,entity_type,entity_id,user_id,api_key_id,detail)VALUES('update','campaign',${id},${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null},${sql.json({version:row.version,content_source:content.source,approval_invalidated:invalidatesApproval})})`;
    return versionedJson(request,row,"campaign",id,row.version);
  }catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;if(error instanceof z.ZodError)return NextResponse.json({error:{code:"validation_error",message:"Datos no válidos",issues:error.issues}},{status:422});console.error(error);return NextResponse.json({error:{code:"campaign_invalid",message:"No se pudo actualizar la campaña"}},{status:422});}
}

export async function DELETE(request:Request,context:{params:Promise<{id:string}>}){
  const principal=await authenticateApiRequest(request,"campaigns:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});
  try{const {id}=await context.params;const version=requireIfMatch(request,"campaign",id);const [campaign]=await sql`UPDATE campaigns SET archived_at=now(),updated_at=now(),version=version+1 WHERE id=${id} AND version=${version} AND status IN('draft','cancelled','completed','failed') RETURNING id,version`;
  if(!campaign)return staleResourceResponse();return versionedJson(request,{archived:true},"campaign",id,campaign.version);}catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;throw error;}
}
