import { NextResponse } from "next/server";
import { z } from "zod";
import { authenticateApiRequest } from "@/lib/api-auth";
import { createImportJob } from "@/lib/data-jobs";
import { sql } from "@/lib/db";

const configSchema=z.object({list_id:z.string().uuid(),mapping:z.record(z.string(),z.string()).optional(),delimiter:z.enum([",",";","\t"]).optional(),initial_status:z.enum(["active","pending"]).default("active"),existing_policy:z.enum(["preserve","fill_empty","overwrite"]).default("fill_empty"),update_unsubscribed:z.boolean().default(true),source:z.string().trim().min(1).max(80).default("csv"),consent_text:z.string().max(5000).default("Importación administrativa"),legal_basis:z.string().max(200).default("consent")});
export const runtime="nodejs";
export async function GET(request:Request){const principal=await authenticateApiRequest(request,"contacts:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});const rows=await sql`SELECT id,type,status,progress,original_filename,total_rows,processed_rows,result,error,errors_storage_key IS NOT NULL AS has_errors,rollback_at,created_at,started_at,completed_at FROM background_jobs WHERE type='contacts_import' ORDER BY created_at DESC LIMIT 100`;return NextResponse.json({data:rows});}
export async function POST(request:Request){const principal=await authenticateApiRequest(request,"contacts:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const form=await request.formData();const file=form.get("file");if(!(file instanceof File))return NextResponse.json({error:{code:"file_required",message:"Selecciona un CSV"}},{status:422});const config=configSchema.parse(JSON.parse(String(form.get("config")??"{}")));const result=await createImportJob(Buffer.from(await file.arrayBuffer()),file.name,config,request.headers.get("idempotency-key")??"",principal.id);return NextResponse.json({...result,status_url:`/api/v1/imports/${result.id}`},{status:202});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:{code:"validation_error",message:"Configuración no válida",issues:error.issues}},{status:422});const message=error instanceof Error?error.message:"No se pudo crear la importación";return NextResponse.json({error:{code:message.includes("Idempotency-Key ya")?"idempotency_conflict":"import_failed",message}},{status:message.includes("Idempotency-Key ya")?409:422});}}
export{configSchema};
