import { NextResponse } from "next/server";
import { z } from "zod";
import { authenticateApiRequest } from "@/lib/api-auth";
import { sql } from "@/lib/db";
import { preconditionResponse,requireIfMatch,staleResourceResponse,versionedJson } from "@/lib/http-concurrency";

const schema=z.object({name:z.string().trim().min(1).max(200).optional(),folder:z.string().trim().max(200).optional(),alt_text:z.string().trim().max(500).optional(),status:z.enum(["active","archived"]).optional()}).refine(value=>Object.keys(value).length>0);

export async function GET(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"templates:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});const{id}=await context.params;const[asset]=await sql`SELECT a.id,a.revision,a.name,a.original_name,a.mime_type,a.byte_size,a.width,a.height,a.folder,a.alt_text,a.sha256,a.created_at,a.updated_at,a.archived_at,count(u.asset_id)::int AS usage_count FROM assets a LEFT JOIN asset_usages u ON u.asset_id=a.id WHERE a.id=${id} GROUP BY a.id`;if(!asset)return NextResponse.json({error:{code:"not_found",message:"Activo no encontrado"}},{status:404});return versionedJson(request,{...asset,url:`/api/v1/assets/${asset.id}/content`},"asset",id,asset.revision);}

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"templates:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const{id}=await context.params;const revision=requireIfMatch(request,"asset",id);const input=schema.parse(await request.json());const[asset]=await sql`UPDATE assets SET name=COALESCE(${input.name??null},name),folder=COALESCE(${input.folder??null},folder),alt_text=COALESCE(${input.alt_text??null},alt_text),archived_at=CASE WHEN ${input.status??null}='archived' THEN now() WHEN ${input.status??null}='active' THEN NULL ELSE archived_at END,updated_at=now() WHERE id=${id} AND revision=${revision} RETURNING id,revision,name,original_name,mime_type,byte_size,width,height,folder,alt_text,sha256,created_at,updated_at,archived_at`;if(!asset)return staleResourceResponse();await sql`INSERT INTO audit_log(action,entity_type,entity_id,user_id,api_key_id,detail)VALUES('update','asset',${id},${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null},${sql.json(input)})`;return versionedJson(request,{...asset,url:`/api/v1/assets/${id}/content`},"asset",id,asset.revision);}catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;if(error instanceof z.ZodError)return NextResponse.json({error:{code:"validation_error",message:"Datos no válidos",issues:error.issues}},{status:422});throw error;}}

export async function DELETE(request:Request,context:{params:Promise<{id:string}>}){const principal=await authenticateApiRequest(request,"templates:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const{id}=await context.params;const revision=requireIfMatch(request,"asset",id);const[asset]=await sql`UPDATE assets SET archived_at=now(),updated_at=now() WHERE id=${id} AND revision=${revision} AND archived_at IS NULL RETURNING id,revision`;if(!asset)return staleResourceResponse();await sql`INSERT INTO audit_log(action,entity_type,entity_id,user_id,api_key_id)VALUES('archive','asset',${id},${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null})`;return versionedJson(request,{archived:true},"asset",id,asset.revision);}catch(error){const precondition=preconditionResponse(error);if(precondition)return precondition;throw error;}}
