import { NextResponse } from "next/server";
import { authenticateApiRequest } from "@/lib/api-auth";
import { sql } from "@/lib/db";
import { flattenSegmentRules,previewSegment,segmentInputSchema,validateSegmentDefinition } from "@/lib/segment-service";
import { versionedItems,versionedJson } from "@/lib/http-concurrency";

export async function GET(request:Request){const principal=await authenticateApiRequest(request,"lists:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});const includeArchived=new URL(request.url).searchParams.get("include_archived")==="true";const data=await sql`SELECT s.*,l.name AS list_name,(SELECT json_agg(h ORDER BY h.captured_on DESC)FROM(SELECT captured_on,contact_count FROM segment_count_history WHERE segment_id=s.id ORDER BY captured_on DESC LIMIT 30)h)AS count_history FROM segments s LEFT JOIN lists l ON l.id=s.list_id WHERE (${includeArchived} OR s.status='active') ORDER BY s.updated_at DESC`;return NextResponse.json({data:versionedItems(data as unknown as {id:string;revision:number}[],"segment")});}

export async function POST(request:Request){const principal=await authenticateApiRequest(request,"lists:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const input=segmentInputSchema.parse(await request.json());const definition=await validateSegmentDefinition(input.list_id,input.definition);const preview=await previewSegment(input.list_id,definition);const stored=JSON.parse(JSON.stringify(definition)) as never;const rules=JSON.parse(JSON.stringify(flattenSegmentRules(definition))) as never;const[segment]=await sql.begin(async tx=>{const[created]=await tx`INSERT INTO segments(name,description,list_id,match_type,rules,definition,last_count,last_count_at)VALUES(${input.name},${input.description},${input.list_id},${definition.match},${tx.json(rules)},${tx.json(stored)},${preview.count},now())RETURNING *`;await tx`INSERT INTO segment_count_history(segment_id,contact_count)VALUES(${created.id},${preview.count})ON CONFLICT(segment_id,captured_on)DO UPDATE SET contact_count=EXCLUDED.contact_count`;await tx`INSERT INTO audit_log(action,entity_type,entity_id,user_id,api_key_id,detail)VALUES('create','segment',${created.id},${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null},${tx.json({list_id:input.list_id,count:preview.count})})`;return[created];});return versionedJson(request,{...segment,preview},"segment",segment.id,segment.revision,201);}catch(error){return NextResponse.json({error:{code:"validation_error",message:error instanceof Error?error.message:"Segmento no válido"}},{status:422});}}
