import { NextResponse } from "next/server";
import { authenticateApiRequest } from "@/lib/api-auth";
import { estimateCampaignAudience } from "@/lib/campaign-service";
import { sql } from "@/lib/db";
import { senderIsAllowed } from "@/lib/deliverability";

export async function GET(request:Request,context:{params:Promise<{id:string}>}){
  const principal=await authenticateApiRequest(request,"campaigns:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});
  try{const {id}=await context.params;const [campaign]=await sql<{subject:string;from_email:string;html_content:string;list_id:string|null;status:string;approval_required:boolean;approved_at:Date|null;approved_version:number|null;version:number;global_sending_paused:boolean;default_from_email:string;allowed_sender_domains:string[]}[]>`SELECT c.subject,c.from_email,c.html_content,c.list_id,c.status,c.approval_required,c.approved_at,c.approved_version,c.version,s.global_sending_paused,s.default_from_email,s.allowed_sender_domains FROM campaigns c CROSS JOIN settings s WHERE c.id=${id}`;
    if(!campaign)return NextResponse.json({error:{code:"not_found",message:"Campaña no encontrada"}},{status:404});const errors=[];const warnings=[];
    if(!campaign.list_id)errors.push({code:"list_missing",message:"Falta la lista principal"});if(!campaign.subject)errors.push({code:"subject_missing",message:"Falta el asunto"});if(!campaign.from_email)errors.push({code:"sender_missing",message:"Falta el remitente"});if(campaign.from_email&&!senderIsAllowed(campaign.from_email,campaign))errors.push({code:"sender_not_allowed",message:"El remitente no está en la lista permitida"});if(campaign.global_sending_paused)errors.push({code:"sending_paused",message:"Los envíos están pausados globalmente"});if(!campaign.html_content)errors.push({code:"content_missing",message:"Falta el contenido"});if(campaign.approval_required&&(!campaign.approved_at||campaign.approved_version!==campaign.version))errors.push({code:"approval_required",message:"La versión actual necesita aprobación administrativa"});
    const variantSenders=await sql<{from_email:string}[]>`SELECT from_email FROM campaign_variants WHERE campaign_id=${id}`;if(variantSenders.some(variant=>!senderIsAllowed(variant.from_email,campaign)))errors.push({code:"variant_sender_not_allowed",message:"Una variante A/B usa un remitente no permitido"});
    if(!/href=["'][^"']+unsubscribe/i.test(campaign.html_content))warnings.push({code:"unsubscribe_injected",message:"El enlace de baja se añadirá automáticamente"});const audience=campaign.list_id?await estimateCampaignAudience(id):null;const[experiment]=await sql<{sample_percentage:number;minimum_sample_size:number;winner_metric:string;wait_minutes:number}[]>`SELECT sample_percentage,minimum_sample_size,winner_metric,wait_minutes FROM campaign_experiments WHERE campaign_id=${id} AND status='configured'`;
    const projectedSample=audience&&experiment?Math.min(Math.max(2,Math.round(audience.included*experiment.sample_percentage/100)),Math.max(0,audience.included-1)):null;if(experiment&&projectedSample!==null&&projectedSample<experiment.minimum_sample_size)warnings.push({code:"experiment_sample_small",message:`La muestra A/B prevista (${projectedSample}) está por debajo del mínimo recomendado (${experiment.minimum_sample_size})`});
    if(audience?.included===0)errors.push({code:"empty_audience",message:"La audiencia no contiene destinatarios enviables"});return NextResponse.json({valid:errors.length===0,errors,warnings,audience,experiment:experiment?{...experiment,projected_sample_size:projectedSample,projected_remainder:audience?audience.included-(projectedSample??0):null}:null});
  }catch(error){return NextResponse.json({error:{code:"preflight_failed",message:error instanceof Error?error.message:"No se pudo validar"}},{status:422});}
}
