import { NextResponse } from "next/server";
import { z } from "zod";
import { sql } from "@/lib/db";
import { apiError,requireApiSession } from "@/lib/http";
const schema=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(1),subject:z.string().trim().min(1),preview_text:z.string().max(200).default(""),from_name:z.string().trim().min(1),from_email:z.email(),reply_to:z.union([z.email(),z.literal("")]).default(""),template_id:z.string().uuid(),list_id:z.string().uuid().optional(),target_type:z.enum(["all","list","tag","segment"]),target_id:z.union([z.string().uuid(),z.null()]).optional(),scheduled_at:z.union([z.string(),z.null()]).optional()});
async function resolved(input:z.infer<typeof schema>){const listId=input.list_id??(input.target_type==="list"?input.target_id:null);if(!listId)throw new Error("Selecciona una lista principal");const[template]=await sql<{published_version_id:string|null;html_content:string;text_content:string}[]>`SELECT published_version_id,html_content,text_content FROM templates WHERE id=${input.template_id} AND status='published'`;if(!template)throw new Error("Plantilla no encontrada");return{listId,template};}
export async function POST(request:Request){const unauthorized=await requireApiSession("campaigns:write");if(unauthorized)return unauthorized;try{const input=schema.parse(await request.json());const{listId,template}=await resolved(input);const status=input.scheduled_at?"scheduled":"draft";const snapshot=JSON.parse(JSON.stringify({template_version_id:template.published_version_id,html:template.html_content,text:template.text_content,created_at:new Date().toISOString()})) as never;const[row]=await sql`INSERT INTO campaigns(name,subject,preview_text,from_name,from_email,reply_to,template_id,template_version_id,list_id,content_source,html_content,text_content,content_snapshot,target_type,target_id,status,scheduled_at)VALUES(${input.name},${input.subject},${input.preview_text},${input.from_name},${input.from_email},${input.reply_to},${input.template_id},${template.published_version_id},${listId},'template',${template.html_content},${template.text_content},${sql.json(snapshot)},${input.target_type==="list"?"all":input.target_type},${input.target_type==="list"?null:input.target_id??null},${status},${input.scheduled_at?new Date(input.scheduled_at):null})RETURNING *`;return NextResponse.json(row,{status:201});}catch(error){return apiError(error);}}
export async function PATCH(request:Request){const unauthorized=await requireApiSession("campaigns:write");if(unauthorized)return unauthorized;try{const input=schema.extend({id:z.string().uuid()}).parse(await request.json());const{listId,template}=await resolved(input);const status=input.scheduled_at?"scheduled":"draft";await sql`UPDATE campaigns SET name=${input.name},subject=${input.subject},preview_text=${input.preview_text},from_name=${input.from_name},from_email=${input.from_email},reply_to=${input.reply_to},template_id=${input.template_id},template_version_id=${template.published_version_id},list_id=${listId},html_content=${template.html_content},text_content=${template.text_content},target_type=${input.target_type==="list"?"all":input.target_type},target_id=${input.target_type==="list"?null:input.target_id??null},status=${status},scheduled_at=${input.scheduled_at?new Date(input.scheduled_at):null},updated_at=now() WHERE id=${input.id} AND status IN('draft','scheduled')`;return NextResponse.json({ok:true});}catch(error){return apiError(error);}}
export async function DELETE(request:Request){const unauthorized=await requireApiSession("campaigns:write");if(unauthorized)return unauthorized;try{const{id}=z.object({id:z.string().uuid()}).parse(await request.json());await sql`UPDATE campaigns SET archived_at=now(),updated_at=now() WHERE id=${id} AND status<>'sending'`;return NextResponse.json({ok:true});}catch(error){return apiError(error);}}
