import { NextResponse } from "next/server";
import { z } from "zod";
import { authenticateApiRequest } from "@/lib/api-auth";
import { sql } from "@/lib/db";
import { versionedItems,versionedJson } from "@/lib/http-concurrency";

const block=z.object({id:z.string().min(1).max(200),type:z.enum(["heading","text","button","image","divider","spacer"]),content:z.string().max(200_000),url:z.string().max(4000).optional(),asset_id:z.string().uuid().optional(),alt:z.string().max(500).optional(),color:z.string().max(50).optional(),align:z.enum(["left","center","right"]).optional(),size:z.number().finite().optional()}).passthrough();
const createSchema=z.object({name:z.string().trim().min(1).max(200),description:z.string().trim().max(1000).default(""),folder:z.string().trim().max(200).default(""),block_document:block});

export async function GET(request:Request){const principal=await authenticateApiRequest(request,"templates:read");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});const url=new URL(request.url);const q=url.searchParams.get("q")?.trim()??"";const includeArchived=url.searchParams.get("include_archived")==="true";const data=await sql`SELECT r.id,r.revision,r.name,r.description,r.folder,r.block_document,r.created_at,r.updated_at,r.archived_at,u.name AS created_by_name FROM reusable_blocks r LEFT JOIN users u ON u.id=r.created_by WHERE (${includeArchived} OR r.archived_at IS NULL) AND (${q}='' OR r.name ILIKE ${`%${q}%`} OR r.description ILIKE ${`%${q}%`}) ORDER BY r.updated_at DESC LIMIT 200`;return NextResponse.json({data:versionedItems(data as unknown as {id:string;revision:number}[],"reusable-block")});}

export async function POST(request:Request){const principal=await authenticateApiRequest(request,"templates:write");if(!principal)return NextResponse.json({error:{code:"unauthorized",message:"No autorizado"}},{status:401});try{const input=createSchema.parse(await request.json());const document=JSON.parse(JSON.stringify(input.block_document)) as never;const[created]=await sql`INSERT INTO reusable_blocks(name,description,folder,block_document,created_by,updated_by)VALUES(${input.name},${input.description},${input.folder},${sql.json(document)},${principal.kind==="session"?principal.id:null},${principal.kind==="session"?principal.id:null})RETURNING *`;await sql`INSERT INTO audit_log(action,entity_type,entity_id,user_id,api_key_id,detail)VALUES('create','reusable_block',${created.id},${principal.kind==="session"?principal.id:null},${principal.kind==="api_key"?principal.id:null},${sql.json({name:input.name})})`;return versionedJson(request,created,"reusable-block",created.id,created.revision,201);}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:{code:"validation_error",message:"Bloque no válido",issues:error.issues}},{status:422});throw error;}}
